### ISSUE TITLE
opendds_idl is inserting path to include file incorrectly - using cmake

### ISSUE THREAD

**Issue by tmaslach** [objectcomputing/OpenDDS#1297] opened 2019-10-02 21:21 UTC
I have attached an example that shows the problem.  Simply run cmake and try to build.  You will get a failure when it attempts to build bTypeSupportImpl.cpp.

[OpenDDSIdlBug.zip](https://github.com/objectcomputing/OpenDDS/files/3683382/OpenDDSIdlBug.zip)

Some explanation:
This project includes an a.idl and b.idl.  b.idl includes a.idl.  
Both idl files are in a subfolder of the project named dds.
I'm using the cmake interface, specifically opendds_target_sources to get the idl files compiled.  Because the idl files are in a subfolder, I have added `OPENDDS_IDL_OPTIONS -I${PROJECT_SOURCE_DIR}/dds` as an argument to opendds_target_sources.   
Cmake generates the project fine, but when opendds_idl runs, it generates the following include in bTypeSupportImpl.cpp:

```C++
#include "dds\aTypeSupportImpl.h"
```

It should be:
```C++
#include "aTypeSupportImpl.h"
```
since all the files are output in the same folder (the build folder).

I'm not sure if the problem is in cmake or opendds_idl.  I suspect it is opendds_idl.  I found this is what the build process calls:
```
opendds_idl.exe -IC:/repos/OpenDDSIdlBug -IC:/repos/OpenDDSIdlBug/dds --default-nested C:/repos/OpenDDSIdlBug/dds/b.idl"
```

This does generate the bad include.  However, if I remove the first -I argument (`-IC:/repos/OpenDDSIdlBug`), everything is generated correctly.  The first -I argument is added automatically by opendds_target_sources, I'm manually adding the second one. 

My workaround right now is to not put these files into a subfolder.  But, that's not a good solution, since the idl files will be in a git submodule.

Thanks!

**Comment by tmaslach** [comment] 2019-10-08 20:02
I forgot to add: I was able to successfully recreate this on Ubuntu.  I did not try any other platform.

**Comment by iguessthislldo** [comment] 2019-10-08 23:17
Yes, this looks like a bug in how `opendds_idl` selects the relative path to include in the `TypeSupportImpl`. It looks like the cmake module is adding the equivalent of `-I${PROJECT_SOURCE_DIR}` for out of source builds before your `-I${PROJECT_SOURCE_DIR}/dds`, but `opendds_idl` is just picking the first include path that matches the include from the IDL file. I will put a PR up shortly to have it pick the longest path that matches, which fixes your example.

Unrelated to that: I had to add `target_link_libraries(OpenDDSIdlBug OpenDDS::OpenDDS)` to `CMakeLists.txt` to get your example to compile. Did you mistakenly leave it out or is what you have in the zip file building for you?

**Comment by tmaslach** [comment] 2019-10-09 00:01
It was a mistake.  I didn't notice, because I was getting the error before the linking step :)  I extracted this out of a more complicated cmake and just missed the line.

Good to here it will get fixed soon - thanks!

**Comment by iguessthislldo** [comment] 2019-10-10 03:21
Alright, thanks for confirming that, just making sure that there wasn't something weird going on in the CMake module.

**Comment by mitza-oci** [comment] 2019-10-10 14:16
@tmaslach please open a pull request for the test csae

**Comment by iguessthislldo** [comment] 2019-10-24 23:28
@mitza-oci I will add a test case in #1315

**Comment by tmaslach** [comment] 2019-10-27 12:23
Sorry, I've been away from my email - has the test been added yet?  I didn't see it in #1315

**Comment by iguessthislldo** [comment] 2019-10-27 21:05
I have a test case that I based on what you uploaded sitting on my computer that works just fine, but I haven't committed and pushed it yet. I have two reasons for this:

1. We don't have any easy to use infrastructure for CMake tests because our support for CMake is so new. Right now we have steps to build and run the two existing CMake tests individually in our build farm setup, where for the MPC based projects it's more or less automatic. I'm thinking we need something easier to use, maybe a `CMakeLists.txt` for all the CMake tests that uses [`ExternalProject`](https://cmake.org/cmake/help/latest/module/ExternalProject.html) or a perl script so some mix of the two.

2. My solution works for your situation, but I'm not convinced it is actually correct for all situations. I'm thinking my solution won't work if the output of the idl compilers were structured into different directories. Our CMake module does put all the output into the same directories though, so maybe I need to see if I can make a MPC example that breaks it.

Either way I need to do some more tinkering.

**Comment by mitza-oci** [comment] 2019-11-19 19:47
@tmaslach I'd like to get a better handle on the root cause of what you're seeing.  Please add a minimal test case to the OpenDDS repository.  Since it is a (potential) bug in opendds_idl, the test case should be independent of build system.

**Comment by tmaslach** [comment] 2019-11-20 02:18
Hi Adam,

Is there any example (or documentation explaining) what precedence I should
follow for such a test?  I assume it would go into the root tests folder?

**Comment by mitza-oci** [comment] 2019-11-22 00:18
Since you're testing `opendds_idl`, add your test to `tests/DCPS/Compiler`.  Make a new subdirectory with a descriptive name.  If it's not obvious you can add a README file describing what's its testing.  Especially if the criteria for passing is successful compilation or if it needs to run the compiled program.

The nice thing about the GitHub pull request system is that we use it for reviews, so you can go ahead and add your code and we can see it before merging.

**Comment by tmaslach** [comment] 2020-01-04 01:31
I've got a first attempt done.   It does display the problem, but also fails the build in an earlier place.  I think I'm doing something slightly wrong in the mpc file I've created, but I'm not sure what.  So, any advice would be helpful:

Here is my mpc file:

```
project: dcps_test_idl_only_lib {
  idlflags      += -SS \
                   -I. \
                   -I./idlfiles
  dcps_ts_flags += -I. \
                   -I./idlfiles
  TypeSupport_Files {
    ./idlfiles/a.idl
    ./idlfiles/b.idl
  }
}
```

The problem is that I am expecting aC.h/cpp and bC.h/cpp to be generated.  But, they don't get generated and the mpc generated vcxproj file also doesn't list it.  What am I doing wrong?   I tried to follow the example of the sibling idl_test_nested_types_lib, but I wanted to avoid creating an export file which that project does.

Here is the location of my github repo: https://github.com/tmaslach/OpenDDS/tree/master/tests/DCPS/Compiler/idl_test_include_line_generation

**Comment by mitza-oci** [comment] 2020-01-09 16:17
This worked for me.  The problem was that the default IDL_Files is `*.idl` in the current directory.
```
project: dcps_test_idl_only_lib {
  idlflags      += -SS \
                   -Iidlfiles
  dcps_ts_flags += -Iidlfiles
  TypeSupport_Files {
    idlfiles/a.idl
    idlfiles/b.idl
  }
  IDL_Files {
    idlfiles
  }
}
```

**Comment by mitza-oci** [comment] 2020-01-17 19:36
This fails, it's explicitly giving it absolute paths that are unnecessary.  Not sure if it's realistic though.
```
project: dcps_test_idl_only_lib {
  idlflags      += -SS \
                   -I$(PWD) -I$(PWD)/idlfiles
  dcps_ts_flags += -I$(PWD) -I$(PWD)/idlfiles
  TypeSupport_Files {
    idlfiles/a.idl
    idlfiles/b.idl
  }
  IDL_Files {
    idlfiles
  }
}
```

**Comment by tmaslach** [comment] 2020-01-24 21:55
Hi Adam,

I have updated the latest at: https://github.com/tmaslach/OpenDDS/blob/master/tests/DCPS/Compiler/idl_test_include_line_generation/idl_test_include_line_generation.mpc.  This accurately reproduces the problem I see in VS.  I've confirmed the VS project also uses '.' to denote the current folder.

```project: dcps_test_idl_only_lib {
  idlflags      += -SS \
                   -I. \
                   -I./idlfiles
  dcps_ts_flags += -I. \
                   -I./idlfiles
  TypeSupport_Files {
    ./idlfiles/a.idl
    ./idlfiles/b.idl
  }
  IDL_Files {
    ./idlfiles
  }
}
```

Regarding the test, what else do you think needs to be done?  It fails when it doesn't build...

**Comment by mitza-oci** [comment] 2020-01-24 22:54
Thanks for the update.  Can you confirm that if `-I.` is removed it starts working?  Then next steps would be to change the CMake module.

**Comment by tmaslach** [comment] 2020-01-28 16:59
I removed the -I. from both idlflags and dcps_ts_flags.  This does make the problem go away.

I agree that this particular use case can be fixed in the cmake module.  But shouldn't specifying '-I.' and '-I./idlfiles' work as well?  I'm thinking that there could be a use case (I'm making it up though) where some idl files are in fact in '.' and others are in the 'idlfiles'.

**Comment by iguessthislldo** [comment] 2022-10-11 16:08
I added a version of the provided IDL as a test and `opendds_idl` include order changes for it in #3315. I think we can call this fixed for now, at least for the IDL that was provided.

**Closed by iguessthislldo** 2022-10-11 16:08 UTC
Labels: bug, intermediate
