### ISSUE TITLE
Add user/project listing to opendds.org

### ISSUE THREAD

**Issue by jwillemsen** [objectcomputing/OpenDDS#1832] opened 2020-08-11 07:44 UTC
In order to let everyone know who is using opendds maybe add a new page to opendds.org with user/project listings like ACE/TAO has http://www.dre.vanderbilt.edu/~schmidt/TAO-users.html. With some short docu about how to create a PR to add a listing to the page the user community can maintain this page directly.

**Comment by mitza-oci** [comment] 2020-08-11 13:08
Duplicate of #512

**Closed by mitza-oci** 2020-08-11 13:08 UTC

**Comment by jwillemsen** [comment] 2021-01-26 10:49
See #2341
