### ISSUE TITLE
pyopendds version 0.1.0 version make problem

### ISSUE THREAD

**Issue by vaibhavgautam** [objectcomputing/OpenDDS#2906] opened 2021-08-12 15:49 UTC
i have successfully installed DDS version 3.17 using ./configure and  make and was trying for pyopendds  but on the make command given in this tutorial given below
https://pyopendds.readthedocs.io/en/latest/getting_started.html gave me this error

python version was 3.8.10
pyopendds version is 0.1.0

error:
make
[ 11%] Generating basicTypeSupportImpl.h, basicTypeSupportImpl.cpp, basicTypeSupport.idl
[ 22%] Generating basicTypeSupportC.h, basicTypeSupportC.inl, basicTypeSupportS.h, basicTypeSupportC.cpp
[ 33%] Generating basicC.h, basicC.inl, basicS.h, basicC.cpp
Scanning dependencies of target basic_idl
[ 44%] Building CXX object CMakeFiles/basic_idl.dir/basicTypeSupportImpl.cpp.o
In file included from /home/crl-ai/anaconda3/envs/Ben_VA/x86_64-conda-linux-gnu/include/c++/9.3.0/bits/locale_facets_nonio.h:39,
                 from /home/crl-ai/anaconda3/envs/Ben_VA/x86_64-conda-linux-gnu/include/c++/9.3.0/locale:41,
                 from /home/crl-ai/anaconda3/envs/Ben_VA/x86_64-conda-linux-gnu/include/c++/9.3.0/iomanip:43,
                 from /home/crl-ai/IPSS/OpenDDS-3.17/dds/DCPS/SafetyProfileStreams.h:13,
                 from /home/crl-ai/IPSS/OpenDDS-3.17/dds/DCPS/TypeSupportImpl.h:15,
                 from /home/crl-ai/IPSS/OpenDDS-3.17/dds/DCPS/XTypes/TypeLookupService.h:13,
                 from /home/crl-ai/IPSS/OpenDDS-3.17/dds/DCPS/Discovery.h:16,
                 from /home/crl-ai/IPSS/OpenDDS-3.17/dds/DCPS/Service_Participant.h:13,
                 from /home/crl-ai/IPSS/pyopendds-master/tests/basic_test/build/basicTypeSupportImpl.h:14,
                 from /home/crl-ai/IPSS/pyopendds-master/tests/basic_test/build/basicTypeSupportImpl.cpp:2:
/home/crl-ai/anaconda3/envs/Ben_VA/x86_64-conda-linux-gnu/include/c++/9.3.0/ctime:80:11: error: '::timespec_get' has not been declared
   80 |   using ::timespec_get;
      |           ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/basic_idl.dir/build.make:124: CMakeFiles/basic_idl.dir/basicTypeSupportImpl.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:97: CMakeFiles/basic_idl.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
</div>

**Comment by mitza-oci** [comment] 2021-08-15 23:19
Duplicate of #2905?

**Closed by mitza-oci** 2021-08-15 23:19 UTC
