### ISSUE TITLE
lib/libOpenDDS_Dcps.so: undefined reference to `.LASF9925' , while make

### ISSUE THREAD

**Issue by KevKzTW** [objectcomputing/OpenDDS#313] opened 2016-10-11 04:05 UTC
Hi 

My system is Ubuntu 14.04 x86_64 in a vagrant in Windows7.

I am trying to install OpenDDS 3.9. 

And I followed the steps "./configure and make" .

Therefore , I got a lot of error messages like title .
Please check the link of screenshot for detail, [http://imgur.com/a/JfKXi
](url)

Now I make failed in /DevGuideExamples and /examples .
Always the same messages .

I have tried to ignore them in /OpenDDS-3.9/GUNmakefile.dist , but there were too many things I should ignore .

I also used no_hidden_visibility = 1 in $(ACE_ROOT)/include/makeinclude/platform_macros.GNU.

I think it should be a system problem or environment setting problem ?

And what are the messages meaning ?

Thanks .

Kev

**Comment by mitza-oci** [comment] 2016-10-11 13:39
Ubuntu 14.04 should work fine.  We don't regularly test on it anymore since 16.04 became available as an LTS.  But before 3.9 was released we had lots of 14.04 testing.  So something isn't set up right, and I'll try to help you fix it.  I don't think setting no_hidden_visibility will be relevant to this.

The screenshot link doesn't seem to have worked.  Please copy and paste (in plain text) the error you're seeing.

**Comment by KevKzTW** [comment] 2016-10-12 01:08
Hey ,

Thanks your help first .

The error messages are : 
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF2860'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF6150'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF6560'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF12508'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF11782'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF11395'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF5017'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF5427'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF5877'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF1517'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF1927'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF5836'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF11745'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF9380'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10253'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF9343'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF9793'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF434'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF479'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF12130'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10292'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF3903'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF3946'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF3989'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10886'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10450'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF7095'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10499'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4008'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4478'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10849'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4433'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4863'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF846'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10413'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10800'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF8591'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF8554'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF8984'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF8517'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF8947'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF3722'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.Ldebug_line0'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF3337'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF3767'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF6282'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF2152'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF2582'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10028'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF7695'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF7658'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF12258'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF12608'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF6245'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF2115'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF2545'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF2500'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF2970'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF6200'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF6670'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF1293'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF12641'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF11641'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF11882'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF11477'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF8223'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF1256'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF1686'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF5186'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF8262'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF11847'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF1219'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF1649'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF5149'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF1604'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF5104'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF5574'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF9450'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF9880'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4182'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF314'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF357'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF9413'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF9843'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF7327'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10986'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10530'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF12291'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4519'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4969'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4143'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4593'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF9806'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF7366'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4926'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4100'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF4550'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF746'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF789'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10900'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF8677'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF3086'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF3047'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF3497'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF3004'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF3454'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF7730'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF2275'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10128'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF10163'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF9029'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF12338'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF9066'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF12373'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF2608'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF6308'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF6758'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF6711'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF11599'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to `.LASF11986'

I just posted a part of them .  (undefined reference to `.LASFXXXX'

Well .... I would try to use Ubuntu 16.04 today .

BTW , the image link was forbidden by Github , so if you copy the link into new browser tab , it should work I think .

Thank you

**Comment by KevKzTW** [comment] 2016-10-12 09:18
Hey ,

I have done make and run the Messenger Example successfully in Ubuntu 16.04 in VirtualBox .

Maybe it's a problem with Vagrant . 
But it's okay for me now .
I will use OpenDDS in Ubuntu 16.04.

If you still want to trace and fix the issue , I can help you test .

Thanks
 :)

**Comment by mitza-oci** [comment] 2016-10-19 18:24
Thanks for the update.  I would like to understand the problem on Ubuntu 14.04 in case someone else runs into it.  As I indicated before, we've done testing on 14.04 and I've never seem a problem like this.  Please capture the entire output from "make" (not just the errors, but the commands it's running, etc) as plain text.

**Comment by mitza-oci** [comment] 2016-10-24 14:16
I'm interested in learning the root cause of this problem.  But if you don't have any further information we should go ahead and close the issue.

**Comment by KevKzTW** [comment] 2016-10-25 01:05
Hey @mitza-oci 

Sorry  ,  I am busy these days.

Would you please wait until this Saturday ?

**Comment by KevKzTW** [comment] 2016-10-28 07:40
Hey @mitza-oci

Is the messages below help you ?

-------------------------------------------------------------------

make[1]: Entering directory `/home/vagrant/OpenDDS-3.9/DevGuideExamples/DCPS/Messenger.minimal'

GNUmakefile: /home/vagrant/OpenDDS-3.9/DevGuideExamples/DCPS/Messenger.minimal/GNUmakefile.MessengerMinimal_Publisher MAKEFLAGS=w

g++ -Wno-deprecated-declarations -fvisibility=hidden -fvisibility-inlines-hidden -ggdb -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE   -I/home/vagrant/OpenDDS-3.9/ACE_wrappers -D__ACE_INLINE__ -I/home/vagrant/OpenDDS-3.9/ACE_wrappers -I/home/vagrant/OpenDDS-3.9/ACE_wrappers/TAO -I../../.. -I../../../tools/modeling/codegen   -Wl,-E -L/home/vagrant/OpenDDS-3.9/ACE_wrappers/lib -L/home/vagrant/OpenDDS-3.9/lib -L.  -L/home/vagrant/OpenDDS-3.9/ACE_wrappers/lib  -L../../../lib  -o publisher .obj/MessengerTypeSupportC.o .obj/MessengerTypeSupportS.o .obj/MessengerC.o .obj/MessengerS.o .obj/MessengerTypeSupportImpl.o .obj/Publisher.o .obj/Boilerplate.o -lOpenDDS_Model -lOpenDDS_Tcp -lOpenDDS_InfoRepoDiscovery -lOpenDDS_Dcps -lTAO_BiDirGIOP -lTAO_PI -lTAO_CodecFactory -lTAO_PortableServer -lTAO_AnyTypeCode -lTAO -lACE -ldl -lrt
make[1]: Leaving directory `/home/vagrant/OpenDDS-3.9/DevGuideExamples/DCPS/Messenger.minimal'

*********Error Message*************
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to.LASF3086'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to.LASFxxxx'
/home/vagrant/OpenDDS-3.9/lib/libOpenDDS_Dcps.so: undefined reference to.LASFxxyy'
.
.
. 
.
*********Error Message*************
collect2: error: ld returned 1 exit status
make[1]: *** [publisher] Error 1
make: *** [MessengerMinimal_Publisher] Error 2

-------------------------------------------------------------------

The error message is too many ... " libOpenDDS_Dcps.so: undefined reference to.LASF" with a number 

Maybe you could install vagrant and use image ubuntu/trusty64 to boot .

I use vagrant 1.8.1

Thanks

**Comment by jwillemsen** [comment] 2016-10-28 07:42
We only need the first undefined reference message, but more important is the output from the point where you give 'make' until the first undefined reference

**Comment by KevKzTW** [comment] 2016-10-28 07:48
Please check it in google driven
[google driven](https://drive.google.com/file/d/0B_F9-w3nnTpzSFhPMEZTcXZWSE0/view?usp=sharing)

**Comment by jwillemsen** [comment] 2016-10-28 07:50
Ok, could you do "make realclean" and a "make" and also put the output on google driven, that would give us all output

**Comment by KevKzTW** [comment] 2016-10-28 08:08
@jwillemsen 

[result2](https://drive.google.com/file/d/0B_F9-w3nnTpzTmVKSTdqRGVpSW8/view?usp=sharing)

thanks

**Comment by jwillemsen** [comment] 2016-10-28 08:17
Are you able to upgrade gcc on this system, looks it has a bug in it, given the internal compiler error it givs in result 2

**Comment by KevKzTW** [comment] 2016-10-28 09:33
Hey @jwillemsen  @mitza-oci 

After "make realclean" , I never saw any message about undefined reference .

Also I upgrade gcc from 4.8 to 5.4 to reduce error .

Finally , I make successfully and run /DevGuildExample/DCPS/Messenger/run_test.pl very well .

Thank you @jwillemsen

**Closed** 2016-10-28 13:51 UTC
Labels: help wanted
